version: '3.8'
services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user_service_db
    ports:
      - 5432:5432
    volumes:
      - user_service_db:/var/lib/postgresql/data
  api:
    container_name: user-service-backend
    build: ./
    env_file:
      - ./.env
    ports:
      - 3000:3000
      # host:container
    environment:
      #- DATABASE_URL=postgresql://postgres:123@localhost:5432/user_service_db?schema=public
      #- DATABASE_URL=postgresql://db/user_service_db
      - DATABASE_URL=postgresql://postgres:5432/user_service_db
      - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
    depends_on:
      - postgres
    volumes:
      - /app:/src
    stdin_open: true
    tty: true

volumes:
  user_service_db:
    driver: local
